# Generated by Django 4.0.3 on 2022-10-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_student_mobile_no_remove_teacher_mobile_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
