# Generated by Django 4.0.3 on 2022-10-22 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_chapter_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courserating',
            options={'verbose_name_plural': '9.Course Rating'},
        ),
        migrations.AlterModelOptions(
            name='studentcourseenrollment',
            options={'verbose_name_plural': '8.Enrolled Courses'},
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='description',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='video',
        ),
        migrations.AddField(
            model_name='course',
            name='course_hours',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='no_lecture',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='skill_level',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('video', models.FileField(null=True, upload_to='chapter_videos/')),
                ('remarks', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.chapter')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
            ],
            options={
                'verbose_name_plural': '7.Section',
            },
        ),
    ]
