# Generated by Django 4.0.3 on 2022-10-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_courserating_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='imageURL',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
