# Generated by Django 4.0.3 on 2022-10-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_section_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='enrollStatus',
            field=models.BooleanField(default=False),
        ),
    ]
