# Generated by Django 4.0.3 on 2022-10-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_chapter_enrollstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='featured_img',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='Catagory_icon',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='video',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
